# Generated by Django 4.2.7 on 2024-05-22 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_produto_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDeProcedimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='produto',
            name='unidade',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
