# Generated by Django 4.2.7 on 2024-05-22 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_tipodeprocedimento_produto_unidade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipodeprocedimento',
            options={'verbose_name': 'Tipo De Produto', 'verbose_name_plural': 'Tipos De Procedimento'},
        ),
    ]
