# Generated by Django 4.2.7 on 2024-05-22 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_tipodeprocedimento_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TipoDeProcedimento',
            new_name='Procedimento',
        ),
    ]
