# Generated by Django 4.2.7 on 2024-05-23 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_tipodeprocedimento_procedimento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='procedimento',
            options={'verbose_name': 'Procedimento', 'verbose_name_plural': 'Procedimento'},
        ),
    ]
