# Generated by Django 4.2.7 on 2024-05-23 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_especialidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apelido', models.CharField(max_length=25)),
                ('nome', models.CharField(max_length=150)),
                ('datanacimento', models.DateField()),
                ('localnascimento', models.CharField(max_length=20)),
                ('nacionalidade', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
            },
        ),
    ]
