# Generated by Django 4.2.7 on 2024-05-23 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_paciente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cirurgia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempoCirurgia', models.IntegerField()),
                ('tempoInternacao', models.IntegerField()),
                ('localInternacao', models.CharField(max_length=100)),
                ('custoTotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('especialidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.especialidade')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.paciente')),
                ('procedimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.procedimento')),
            ],
        ),
    ]
