# Generated by Django 4.2.7 on 2024-05-25 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_cirurgia_options_linhascirurgia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familia', models.CharField(max_length=10)),
                ('descricao', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Familias',
                'verbose_name_plural': 'Familia',
            },
        ),
    ]
