# Generated by Django 4.2.7 on 2024-05-25 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_familia'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='familia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.familia'),
        ),
        migrations.AddField(
            model_name='produto',
            name='tipoCusto',
            field=models.TextField(choices=[('CUSTO FIXO', 'Custo Fixo'), ('CUSTO VARIAVEL', 'Custo Variavel')], null=True),
        ),
    ]
