# Generated by Django 4.2.7 on 2024-05-25 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_produto_familia_produto_tipocusto'),
    ]

    operations = [
        migrations.AddField(
            model_name='cirurgia',
            name='custoFixo',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cirurgia',
            name='custoVariavel',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
