# Generated by Django 4.2.7 on 2024-05-27 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_cirurgia_custofixo_cirurgia_custovariavel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linhascirurgia',
            name='quantidade',
            field=models.IntegerField(),
        ),
    ]
