# Generated by Django 4.2.7 on 2024-05-27 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_linhascirurgia_quantidade'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LinhasCirurgia',
        ),
    ]
