# Generated by Django 4.2.7 on 2024-05-27 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_delete_linhascirurgia'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinhasCirurgia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=150)),
                ('custoUnitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantidade', models.IntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cirurgia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cirurgia')),
                ('codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.produto')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.unidade')),
            ],
            options={
                'verbose_name': 'LinhaCirurgia',
                'verbose_name_plural': 'LinhasCirurgias',
            },
        ),
    ]
