# Generated by Django 5.0.6 on 2024-06-07 22:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_linhascirurgia'),
    ]

    operations = [
        migrations.AddField(
            model_name='cirurgia',
            name='data',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
