# Generated by Django 5.0.6 on 2024-06-27 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_produto_unidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linhascirurgia',
            name='custoUnitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='linhascirurgia',
            name='descricao',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='linhascirurgia',
            name='unidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.unidade'),
        ),
    ]
