# Generated by Django 5.0.6 on 2024-07-01 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_linhascirurgia_custounitario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PorteCirurgico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=150)),
                ('tempo', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'PorteCirurgico',
                'verbose_name_plural': 'PorteCirurgico',
            },
        ),
        migrations.CreateModel(
            name='PorteCirurgicoCirurgia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('porteCirurgico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.portecirurgico')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.produto')),
            ],
            options={
                'verbose_name': 'PorteCirurgicoCirurgia',
                'verbose_name_plural': 'PorteCirurgicoCirurgias',
            },
        ),
    ]
