# Generated by Django 5.0.6 on 2024-07-01 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_portecirurgico_portecirurgicocirurgia'),
    ]

    operations = [
        migrations.AddField(
            model_name='cirurgia',
            name='porteCirurgico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.portecirurgico'),
        ),
    ]
