# Generated by Django 5.0.6 on 2024-07-01 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_cirurgia_portecirurgico'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portecirurgico',
            options={'verbose_name': 'PorteCirurgico', 'verbose_name_plural': 'PorteCirurgicos'},
        ),
        migrations.RenameField(
            model_name='cirurgia',
            old_name='porteCirurgico',
            new_name='portecirurgico',
        ),
        migrations.RenameField(
            model_name='portecirurgicocirurgia',
            old_name='porteCirurgico',
            new_name='descricao',
        ),
        migrations.RemoveField(
            model_name='portecirurgico',
            name='tempo',
        ),
        migrations.AddField(
            model_name='portecirurgico',
            name='tempo_minutos',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
